import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {acbLogin} from '../server/account.ts';import {authenticate} from '../server/acb.ts';import {hash,encrypt,decrypt} from '../server/crypto.ts';import {sessionIdentity,logout,COOKIE,sessionCookie} from '../server/sessions.ts';
import {action} from '../server/service.ts';
const owner={userId:'owner',displayName:'Javier'};const key='a1'.repeat(32);
function fetcher(sub='stable-id',name='Pedro'){return async url=>url.endsWith('/signIn')?Response.json({code:'code',UserData:{UserAttributes:[{Name:'sub',Value:sub},{Name:'preferred_username',Value:name}]}}):url.endsWith('/getTokens')?Response.json({jwt:'test-jwt',type:'Bearer'}):Response.json([{userTeamList:[{idUserTeam:12,nameTeam:'Equipo'}]}]);}
async function setup(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));db.prepare('INSERT INTO leagues VALUES(?,?,?,?)').run('league','Amigos','owner',await hash('invitation'));db.prepare('INSERT INTO members VALUES(?,?,?)').run('owner','league','Javier');
 function prepare(q){let args=[];return{bind(...a){args=a;return this;},async first(){const r=db.prepare(q).get(...args);return r?{...r}:null;},async run(){return{meta:{changes:db.prepare(q).run(...args).changes}};},async all(){return{results:db.prepare(q).all(...args)};}};}
 let queue=Promise.resolve();const env={TOKEN_ENCRYPTION_KEY:key,DB:{prepare,batch(statements){const task=queue.then(async()=>{db.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}});queue=task.catch(()=>{});return task;}}};return{db,env};}
const body=(extra={})=>({username:'user@example.test',password:'fake-test-password',code:'invitation',...extra});
test('owner removal deletes dependent data and revokes sessions, preserving owner and other leagues',async()=>{const{db,env}=await setup();try{
 const guest=await acbLogin(env,body(),null,fetcher());
 db.prepare('INSERT INTO rounds(id,league_id,label,lock_at,ends_at) VALUES(?,?,?,?,?)').run('r','league','Xornada',1,2);
 db.prepare('INSERT INTO snapshots(round_id,user_id,team_id,team_name,players_json,imported_at,raw_points) VALUES(?,?,?,?,?,?,?)').run('r',guest.userId,'12','Equipo','[]',1,203);
 await assert.rejects(action(env,{userId:guest.userId,displayName:'Pedro'},'remove-member',{userId:'owner'}),{code:'OWNER_ONLY'});
 await assert.rejects(action(env,owner,'remove-member',{userId:'owner'}),{code:'OWNER_PROTECTED'});
 db.prepare('INSERT INTO leagues VALUES(?,?,?,?)').run('other','Other','outsider','other-hash');db.prepare('INSERT INTO members VALUES(?,?,?)').run('outsider','other','Other');
 await assert.rejects(action(env,owner,'remove-member',{userId:'outsider'}),{code:'MEMBER_NOT_FOUND'});
 await action(env,owner,'remove-member',{userId:guest.userId});
 for(const table of ['sessions','acb_identities','acb_links','snapshots','members'])assert.equal(db.prepare(`SELECT COUNT(*) n FROM ${table} WHERE user_id=?`).get(guest.userId).n,0);
 assert.equal(await sessionIdentity(env,guest.session),null);assert.equal(db.prepare('SELECT COUNT(*) n FROM members').get().n,2);
 await assert.rejects(action(env,owner,'remove-member',{userId:guest.userId}),{code:'MEMBER_NOT_FOUND'});
 }finally{db.close();}});
test('ACB login trusts authenticated sub, not typed email; repeat login keeps same member',async()=>{const{db,env}=await setup();try{const input=body();const first=await acbLogin(env,input,null,fetcher());assert.equal(input.password,undefined);assert.deepEqual(await sessionIdentity(env,first.session),{userId:first.userId,displayName:'Pedro'});const second=await acbLogin(env,body({username:'changed@example.test',code:''}),null,fetcher());assert.equal(second.userId,first.userId);assert.equal(db.prepare('SELECT COUNT(*) n FROM members').get().n,2);const stored=db.prepare('SELECT jwt FROM acb_links').get().jwt;assert.notEqual(stored,'test-jwt');assert.equal(await decrypt(stored,key,first.userId),'test-jwt');assert.notEqual(db.prepare('SELECT token_hash FROM sessions LIMIT 1').get().token_hash,first.session);}finally{db.close();}});
test('valid ACB login without valid league invitation cannot create an account',async()=>{const{db,env}=await setup();try{await assert.rejects(acbLogin(env,body({code:'bad'}),null,fetcher()),{code:'INVALID_INVITE'});assert.equal(db.prepare('SELECT COUNT(*) n FROM members').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);}finally{db.close();}});
test('rejected ACB login or missing stable identity cannot create or claim an account',async()=>{const{db,env}=await setup();try{await assert.rejects(acbLogin(env,body(),null,async()=>new Response(null,{status:401})),{code:'RECONNECT'});await assert.rejects(acbLogin(env,body(),null,fetcher('')),{code:'ACB_IDENTITY'});assert.equal(db.prepare('SELECT COUNT(*) n FROM acb_identities').get().n,0);}finally{db.close();}});
test('owner migration preserves owner ID, team choice and previously encrypted data',async()=>{const{db,env}=await setup();try{db.prepare('INSERT INTO acb_links(user_id,jwt,expires_at,teams_json,team_id,team_name) VALUES(?,?,?,?,?,?)').run('owner',await encrypt('old',key,'owner'),9999999999999,'[]','12','Equipo');const result=await acbLogin(env,body({migrate:true}),owner,fetcher());assert.equal(result.userId,'owner');assert.equal(db.prepare('SELECT owner_id FROM leagues').get().owner_id,'owner');assert.equal(db.prepare('SELECT team_id FROM acb_links').get().team_id,'12');assert.equal(await decrypt(db.prepare('SELECT jwt FROM acb_links').get().jwt,key,'owner'),'test-jwt');assert.equal((await acbLogin(env,body({code:''}),null,fetcher())).userId,'owner');}finally{db.close();}});
test('migration cannot steal an ACB identity or replace an existing binding',async()=>{const{db,env}=await setup();try{const guest=await acbLogin(env,body(),null,fetcher('guest'));await assert.rejects(acbLogin(env,body({migrate:true}),owner,fetcher('guest')),{code:'ACCOUNT_LINKED'});await acbLogin(env,body({migrate:true}),owner,fetcher('owner-acb'));await assert.rejects(acbLogin(env,body({migrate:true}),owner,fetcher('other')),{code:'ACCOUNT_MISMATCH'});await assert.rejects(acbLogin(env,body({migrate:true}),{userId:guest.userId},fetcher('third')),{code:'OWNER_ONLY'});}finally{db.close();}});
test('parallel first sign-ins cannot create duplicate identities or leave orphan members',async()=>{const{db,env}=await setup();try{const results=await Promise.allSettled([acbLogin(env,body(),null,fetcher()),acbLogin(env,body(),null,fetcher())]);assert(results.some(r=>r.status==='fulfilled'));assert.equal(db.prepare('SELECT COUNT(*) n FROM acb_identities').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM members').get().n,2);}finally{db.close();}});
test('logout, expired or forged sessions fail closed; cookies protect the session',async()=>{const{db,env}=await setup();try{const first=await acbLogin(env,body(),null,fetcher());assert.match(sessionCookie(first.session),/HttpOnly; Secure; SameSite=Lax/);await logout(env,new Request('https://site.test/',{headers:{cookie:COOKIE+'='+first.session}}));assert.equal(await sessionIdentity(env,first.session),null);const second=await acbLogin(env,body(),null,fetcher());db.exec('UPDATE sessions SET expires_at=0');assert.equal(await sessionIdentity(env,second.session),null);assert.equal(await sessionIdentity(env,'a'.repeat(64)),null);}finally{db.close();}});
test('ACB identity is not inferred from a code, email, nickname or unverified JWT',async()=>{await assert.rejects(authenticate('victim@example.test','fake',async u=>Response.json(u.endsWith('/signIn')?{code:'code',UserData:{UserAttributes:[{Name:'email',Value:'victim@example.test'}]}}:{jwt:'ey.fake.jwt',type:'Bearer'})),{code:'ACB_IDENTITY'});});
