'use client';
import {useState,useEffect,useCallback,useRef,type FormEvent} from 'react';
import {LayoutGrid,Users,Link2,ShieldCheck,Layers3,Fingerprint,RefreshCw,ArrowRight,Settings2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogClose,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import LeagueBoard from '@/components/league-board';
import AcbLogin,{authApi} from '@/components/acb-login';
import {ScoreRefresh,AuditLog} from '@/components/admin-tools';
import {CatalogReview} from '@/components/catalog-review';
import Standings from '@/components/standings';
import BrokerStandings from '@/components/broker-standings';
import type {BrokerRow} from '@/lib/broker';
import {selectRound} from '@/lib/round-selection';
import OverallStandings from '@/components/overall-standings';
import type {OverallRow} from '@/lib/model';
import {Checkbox} from '@/components/ui/checkbox';
import {demoLineups} from '@/lib/demo';
import {compare,overlap,type Lineup,type Round} from '@/lib/model';
type State={broker?:{round:BrokerRow[];overall:BrokerRow[]};overall?:OverallRow[];acbLinked?:boolean;hidden?:boolean;signedIn:boolean;user?:{id:string;name:string};league?:{id:string;name:string;isOwner:boolean}|null;members?:{id:string;name:string;declared?:number}[];rounds?:Round[];round?:Round|null;lineups?:Lineup[];connection?:{connected:boolean;expiresAt:number;teamId:string|null;teamName:string|null;teams:{id:string;name:string}[]}|null};
async function api(action?:string,data:Record<string,unknown>={},round?:string){
 const response=await fetch(`/api/league${round?`?round=${encodeURIComponent(round)}`:''}`,action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})}:{cache:'no-store'});
 let result;try{result=await response.json() as State & {error?:string;inviteCode?:string};}catch{throw new Error('Non se puido cargar a liga. Téntao de novo.');}
 if(!response.ok)throw new Error(result.error??'Non se puido completar a operación.');return result;
}
function formData(event:FormEvent<HTMLFormElement>){event.preventDefault();return Object.fromEntries(new FormData(event.currentTarget).entries());}
function Picker({value,onChange,options,label}:{value:string;onChange:(value:string)=>void;options:{id:string;name:string}[];label:string}){return <Select value={value||undefined} onValueChange={onChange}><SelectTrigger className="round-picker" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select>;}
export default function LeagueApp(){
 const [data,setData]=useState<State>({signedIn:false});const [loading,setLoading]=useState(true);const [demo,setDemo]=useState(false);
 const [rosterUser,setRosterUser]=useState('');const [sortBy,setSortBy]=useState('position');const [direction,setDirection]=useState('asc');const [metric,setMetric]=useState('net');
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('quinteto-sort-'+(data.user?.id??'demo'))??'{}');setSortBy(p.by==='coincidences'?'coincidences':'position');setDirection(p.direction==='desc'?'desc':'asc');}catch{}},[data.user?.id]);
 const saveSort=(by:string,dir:string)=>{setSortBy(by);setDirection(dir);try{localStorage.setItem('quinteto-sort-'+(data.user?.id??'demo'),JSON.stringify({by,direction:dir}));}catch{}};
 const [tab,setTab]=useState('compare');const rankings=tab==='standings'||tab==='overall';const [filter,setFilter]=useState('all');const [account,setAccount]=useState(false);
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [modal,setModal]=useState('');const [invite,setInvite]=useState('');
 const [declareStart,setDeclareStart]=useState(false);const [closeRound,setCloseRound]=useState(false);const [roundId,setRoundId]=useState('');const [teamId,setTeamId]=useState('');const [reference,setReference]=useState('');const [clock,setClock]=useState(Date.now());
 const [removeMember,setRemoveMember]=useState<{id:string;name:string}|null>(null);
 const initialized=useRef(false);const autoAttempt=useRef('');const operation=useRef(false);
 const refresh=useCallback(async()=>{const next:State=await api(undefined,{},roundId);setData(next);if(!initialized.current){setDemo(false);initialized.current=true;}return next;},[roundId]);
 useEffect(()=>{let active=true;refresh().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[refresh]);
 useEffect(()=>{const timer=setInterval(()=>{setClock(Date.now());if(!document.hidden){void refresh().catch(()=>{});if(data.signedIn&&data.league)void api('ping').catch(()=>{});}},60000);return()=>clearInterval(timer);},[refresh,data.signedIn,data.league?.id]);
 const run=useCallback(async(action:string,body:Record<string,unknown>={},success?:string)=>{
  if(operation.current)return null;operation.current=true;setBusy(true);setError('');
  try{const result=await api(action,body);await refresh();if(success)toast.success(success);return result;}catch(e){setError(e instanceof Error?e.message:'Produciuse un erro.');return null;}finally{operation.current=false;setBusy(false);}
 },[refresh]);
 const automaticRound=selectRound(data.rounds??[],clock); const autoRound=automaticRound?.closedAt===null&&automaticRound.endsAt>clock?automaticRound:undefined;
 const openRound=data.round&&data.round.closedAt===null&&data.round.endsAt>clock?data.round:undefined;
 useEffect(()=>{setDeclareStart(false);},[data.round?.id]);
 const hidden=!demo&&data.hidden!==false;
 useEffect(()=>{
  if(demo||!data.connection?.connected||!data.connection.teamId||busy)return;
  const own=data.round?.id===autoRound?.id?data.lineups?.find(t=>t.userId===data.user?.id):undefined;
  const slot=Math.floor(Date.now()/300000);const key=`${autoRound?.id??'between'}:${data.connection.teamId}:${data.connection.expiresAt}:${slot}`;
  if(autoAttempt.current===key||own&&Date.now()-own.importedAt<300000)return;
  autoAttempt.current=key;void run('refresh-team',{roundId:autoRound?.id});
 },[data,demo,autoRound,busy,run]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
  if(!context)return;const lifecycle=new AbortController();
  const register=async()=>{try{await context.registerTool({name:'read_league_comparison',description:'Le os cadros de xogadores que se mostran e indica se son unha demostración.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Non se admiten parámetros.');const lineups=demo?demoLineups:data.lineups??[];return {demo,round:demo?'Exemplo':data.round?.label,players:compare(lineups)};}},{signal:lifecycle.signal});}catch{/* Optional browser capability. */}};void register();return()=>lifecycle.abort();
 },[demo,data]);
 const lineups=demo?demoLineups:data.lineups??[];const rows=compare(lineups);const memberCount=demo?4:data.members?.length??0;
 const ref=lineups.find(t=>t.userId===reference)??lineups.find(t=>t.userId===data.user?.id)??lineups[0];
 const submitLeague=async(e:FormEvent<HTMLFormElement>,action:string)=>{const result=await run(action,formData(e),'Xa estás na liga');if(result){if(result.inviteCode)setInvite(result.inviteCode);setDemo(false);setAccount(false);}};
 const selectTeam=async()=>{const selected=await run('select-team',{teamId},'Equipo seleccionado');if(selected&&autoRound)await run('import',{roundId:autoRound.id},'Cadro importado');};
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark">q.</span>quinteto</div><div className="league-info"><div className="eyebrow">A TÚA LIGA PRIVADA</div><div className="league-name">{demo?'A liga dos colegas':data.league?.name??'A túa próxima liga'}</div></div><nav><button aria-label="Equipos e xornada" className={`nav-button ${!account&&!rankings?'active':''}`} onClick={()=>{setAccount(false);setTab('compare');}}><LayoutGrid size={19}/><span>Equipos e xornada</span></button><button aria-label="Clasificacións" className={`nav-button ${!account&&rankings?'active':''}`} onClick={()=>{setAccount(false);setTab('standings');}}><Users size={19}/><span>Clasificacións</span></button><button aria-label="A miña liga e conta" className={`nav-button ${account?'active':''}`} onClick={()=>{setAccount(true);setDemo(false);}}><Settings2 size={19}/><span>A miña liga e conta</span></button></nav><div className="sidebar-bottom"><ShieldCheck size={21}/><p>A rivalidade queda<br/>entre amigos.</p></div></aside>
  <main className="main"><header className="topbar"><strong>SuperManager · Liga privada</strong><span className="user">{demo?<span className="status-pill">Vista de exemplo</span>:<span>{data.user?.name??'Benvido'}</span>}<span className="avatar a0">{(data.user?.name??'Q').slice(0,2).toUpperCase()}</span></span></header>
  <div className="content"><div className="page-heading"><div><div className="eyebrow">{account?'O TEU RECUNCHO NA LIGA':'TODOS OS EQUIPOS, UNHA LOUSA'}</div><h1>{account?'A miña liga e o meu equipo.':rankings?'Clasificacións da liga.':'Así xogamos esta xornada.'}</h1><p>{account?'Conecta a túa conta e deixa as capturas atrás.':rankings?'Consulta cada xornada ou o acumulado da liga.':'Quen coincide contigo. Quen aposta diferente.'}</p></div>{!account&&(demo?<span className="button">Xornada de exemplo</span>:data.rounds?.length?<Picker value={data.round?.id??''} onChange={setRoundId} label="Xornada" options={data.rounds.map(r=>({id:r.id,name:r.label}))}/>:null)}</div>
  {error&&<div className="error" role="alert">{error} <button className="text-button" onClick={()=>{setError('');void refresh().catch(e=>setError(e.message));}}>Tentar de novo</button></div>}
  {demo&&<div className="demo-banner"><span><b>Estás a ver unha demostración.</b> Equipos e xogadores ficticios.</span><button className="text-button" onClick={()=>{setDemo(false);setAccount(!data.league);}}>Ir á miña liga</button></div>}
  {loading&&<p className="loading" role="status">Cargando a túa liga…</p>}
  {!demo&&data.signedIn&&data.league?.isOwner&&data.round&&data.round.lockAt<=clock&&<div hidden={account}><ScoreRefresh key={data.round.id} round={data.round} onUpdated={refresh}/></div>}
  {!demo&&!data.signedIn&&!loading?<div><AcbLogin/><p className="subtle" style={{marginTop:20}}><a href="/signin-with-chatgpt?return_to=%2Frecover" target="_top">Recuperar o acceso anterior do administrador</a></p></div>:
  !demo&&data.signedIn&&!data.league?<div className="account-grid"><section className="panel"><h2>Crea a vosa liga</h2><p className="subtle" style={{marginBottom:20}}>Serás quen configure o horario de cada xornada.</p><form className="form" onSubmit={e=>void submitLeague(e,'create')}><label>O teu nome<input name="name" required maxLength={40} placeholder="Como che chaman os teus amigos"/></label><label>Nome da liga<input name="leagueName" required maxLength={80} placeholder="A liga dos colegas"/></label><button className="button primary" disabled={busy}>Crear liga</button></form></section><section className="panel"><h2>Xa teño un convite</h2><p className="subtle" style={{marginBottom:20}}>Pídelle o código a quen creou a vosa liga.</p><form className="form" onSubmit={e=>void submitLeague(e,'join')}><label>O teu nome<input name="name" required maxLength={40}/></label><label>Código de convite<input name="code" required maxLength={64} autoComplete="off"/></label><button className="button" disabled={busy}>Unirme á liga</button></form></section></div>:
  account&&!demo?<div className="account-grid"><section className="panel"><h2>Conta ACB</h2><p className="subtle" style={{margin:'12px 0 20px'}}>{data.connection?.connected?'Conta conectada. Selecciona o equipo que queres compartir.':'Conecta a túa conta para consultar os teus equipos de SuperManager.'}</p>{data.connection?.connected?<><Picker label="O teu equipo de SuperManager" value={teamId||data.connection.teamId||''} onChange={setTeamId} options={data.connection.teams}/>{!data.connection.teams.length&&<p className="subtle">Esta conta non ten equipos dispoñibles.</p>}<div className="action-row"><button className="button primary" disabled={busy||!teamId} onClick={()=>void selectTeam()}>Seleccionar e importar</button><button className="button" disabled={busy} onClick={()=>void run('disconnect',{},'Conta desvinculada')}>Desvincular ACB</button></div><p className="subtle" style={{marginTop:20}}>Actualizamos cada cinco minutos mentres a web está aberta, tamén entre xornadas. Só despois de declarar o equipo inicial e durante a xornada, os cambios quedan rexistrados para que o administrador introduza o axuste de puntos da xornada. Cando caduque a sesión terás que volver conectar.</p></>:<button className="button primary" onClick={()=>setModal('connect')}>Conectar ACB</button>}</section><section className="panel"><h2>{data.league?.name}</h2><p className="subtle" style={{marginTop:12}}>{memberCount} membros · {data.league?.isOwner?'Es o creador da liga':'Membro da liga'}</p>{data.members?.map(m=><div key={m.id} style={{marginTop:12,display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><span>{m.name}{m.id===data.user?.id?' (ti)':''}</span>{data.league?.isOwner&&m.id!==data.user?.id&&<button className="text-button" disabled={busy} aria-label={`Eliminar participante ${m.name}`} onClick={()=>setRemoveMember(m)}>Eliminar</button>}</div>)}{data.league?.isOwner&&<div className="action-row"><button className="button" disabled={busy} onClick={async()=>{const r=await run('invite');if(r?.inviteCode)setInvite(r.inviteCode);}}>Xerar un novo convite</button><button className="button" disabled={busy} onClick={()=>setModal('round')}>Nova xornada</button>{openRound&&openRound.lockAt<=clock&&<button className="button" onClick={()=>setCloseRound(true)}>Rematar xornada</button>}</div>}<p className="subtle" style={{marginTop:20}}>Comparte a ligazón da web e o código de convite. Cada colega entra coa súa conta ACB; non necesita ChatGPT.</p><div className="action-row"><button className="text-button" onClick={()=>{setDemo(true);setAccount(false);}}>Ver a demostración</button><button className="text-button" onClick={()=>void authApi('logout').then(()=>location.assign('/')).catch(e=>setError(e.message))}>Saír</button></div></section>{data.league?.isOwner&&!data.acbLinked&&<AcbLogin migrate/>}{data.league?.isOwner&&<CatalogReview/>}{data.league?.isOwner&&<AuditLog/>}</div>:
  <>
   {!rankings&&<>{!demo&&data.round&&<section className="panel" style={{padding:18,marginBottom:18}}><h2>Equipos iniciais · {data.round.label}</h2><div className="action-row">{data.members?.map(m=><div key={m.id} className={m.declared?'declaration-badge declared':'declaration-badge'}><b>{m.name}</b><span>{m.declared?'✓ Equipo inicial declarado':'◷ Pendente de declarar'}</span></div>)}</div></section>}
   {!demo&&<div className="toolbar"><p className="subtle">{data.round?`${data.round.closedAt||data.round.endsAt<=clock?'Rematada · inicio':data.round.lockAt<=clock?'En xogo · inicio':'Inicio'} · ${new Date(data.round.lockAt).toLocaleString('gl-ES')}`:'O creador da liga debe abrir unha xornada.'}</p><div className="action-row" style={{margin:0}}>{data.league?.isOwner&&<button className="button" onClick={()=>setModal('round')}>Nova xornada</button>}<button className="button primary" disabled={busy||!data.connection?.connected||!data.connection.teamId||!openRound} onClick={async()=>{const result=await run('import',{roundId:openRound?.id,declareStartingTeam:declareStart},declareStart?'Equipo inicial declarado':'Cadro actualizado');if(result)setDeclareStart(false);}}><RefreshCw size={16}/>{busy?'Actualizando…':'Actualizar o meu cadro'}</button></div></div>}
   <p className="subtle">Regra da liga: mínimo 2 xogadores en total entre Río Breogán, Leyma Coruña e Obradoiro. Pódense mesturar clubs.</p>
   {!demo&&openRound&&!data.members?.find(m=>m.id===data.user?.id)?.declared&&<div className="declaration"><Checkbox id="declare-start" checked={declareStart} disabled={busy||!!data.lineups?.find(t=>t.userId===data.user?.id)?.declaredAt} onCheckedChange={value=>setDeclareStart(value===true)}/><label htmlFor="declare-start">Este era o meu equipo ao inicio da xornada <small>Declaración de honra, aínda que o rexistres despois. Marca e preme «Actualizar o meu cadro». Antes desta declaración non se contabiliza ningunha penalización. Só se pode declarar unha vez.</small></label></div>}
   {hidden&&<div className="demo-banner"><span><b>Cadros ocultos ata o inicio.</b> Só ti podes ver o teu equipo. As coincidencias e apostas únicas mostraranse cando comece a xornada.</span></div>}
   {!hidden&&<div className="stats"><div className="stat"><div><small>Equipos na lousa</small><strong>{lineups.length} <small>/ {memberCount}</small></strong></div><Users className="stat-icon" size={46}/></div><div className="stat"><div><small>Comúns entre os publicados</small><strong>{lineups.length>1?rows.filter(p=>p.owners.length===lineups.length).length:'—'}</strong></div><Layers3 className="stat-icon" size={46}/></div><div className="stat"><div><small>Apostas únicas</small><strong>{lineups.length>1?rows.filter(p=>p.owners.length===1).length:'—'}</strong></div><Fingerprint className="stat-icon" size={46}/></div></div>}
   {!demo&&!hidden&&lineups.length<memberCount&&<p className="subtle" style={{marginBottom:16}}>Faltan {memberCount-lineups.length} cadros. As coincidencias calcúlanse só entre os equipos publicados.</p>}
   </>}
   <Tabs value={tab} onValueChange={setTab} className="view-tabs"><TabsList>{rankings?<><TabsTrigger value="standings">Clasificación da xornada</TabsTrigger><TabsTrigger value="overall">Clasificación xeral</TabsTrigger></>:<><TabsTrigger value="compare">{hidden?'O meu cadro':'Comparar cadros'}</TabsTrigger><TabsTrigger value="teams">Por equipo</TabsTrigger></>}</TabsList></Tabs>
   {rankings&&<label className="action-row">Ordenar clasificación por <select aria-label="Puntuación da clasificación" value={metric} onChange={e=>setMetric(e.target.value)}><option value="acb">Puntos ACB</option><option value="net">Puntos tras penalizacións</option><option value="broker">Broker</option></select></label>}
   {!rankings&&tab==='compare'&&!hidden&&<div className="action-row"><label>Ordenar <select aria-label="Ordenar xogadores" value={sortBy} onChange={e=>saveSort(e.target.value,direction)}><option value="position">Posto e nome</option><option value="coincidences">Coincidencias</option></select></label><label>Sentido <select aria-label="Sentido da orde" value={direction} onChange={e=>saveSort(sortBy,e.target.value)}><option value="asc">De menor a maior / A–Z</option><option value="desc">De maior a menor / Z–A</option></select></label></div>}
   {rankings&&metric==='broker'?<BrokerStandings overall={tab==='overall'} rows={(tab==='overall'?data.broker?.overall:data.broker?.round)??[]}/>:tab==='overall'&&!demo?<OverallStandings metric={metric} rows={data.overall??[]}/>:<div className="workspace" style={rankings?{gridTemplateColumns:"1fr"}:undefined}><div><div className="toolbar"><h2>{hidden?'O meu cadro oculto':tab==='compare'?'A lousa':tab==='standings'?'Clasificación da xornada':'Os equipos'}</h2>{!hidden&&tab==='compare'&&<div className="filters">{[['all','Todos'],['common','En común'],['unique','Diferenciais']].map(([id,label])=><button aria-pressed={filter===id} className={`filter ${filter===id?'selected':''}`} key={id} onClick={()=>{setFilter(id);setRosterUser('');}}>{label}</button>)}<select aria-label="Filtrar por plantilla" value={lineups.some(t=>t.userId===rosterUser)?rosterUser:''} onChange={e=>{setRosterUser(e.target.value);setFilter('all');}}><option value="">Todas as plantillas</option>{lineups.map(t=><option value={t.userId} key={t.userId}>Plantilla de {t.name}</option>)}</select></div>}</div>{tab==='standings'?(hidden?<p className="panel empty">A clasificación estará dispoñible cando comece a xornada.</p>:<Standings metric={metric} admin={!demo&&!!data.league?.isOwner} onPenalty={(userId,penalty)=>run('penalty',{roundId:data.round?.id,userId,penalty},'Axuste gardado')} lineups={lineups} demo={demo} editable={!demo&&!!data.league?.isOwner&&!!data.round&&(!!data.round.closedAt||data.round.endsAt<=clock)} busy={busy} onScore={(userId,points)=>run('score',{roundId:data.round?.id,userId,points},'Puntuación gardada')}/>):<LeagueBoard rosterUser={!hidden&&lineups.some(t=>t.userId===rosterUser)?rosterUser:''} sortBy={sortBy} direction={direction} lineups={lineups} tab={hidden?'teams':tab} filter={hidden?'all':filter} hidden={hidden}/>}</div>
   {!rankings&&<div className="side-stack"><div className="panel side-card accent-card"><Link2 size={25}/><h3 style={{marginTop:14}}>{!demo&&data.connection?.teamName?data.connection.teamName:'O teu equipo, sen capturas.'}</h3><p>{!demo&&data.connection?.connected?'A túa conta está conectada. Xestiona o teu equipo ou cambia a conexión.':'Conecta ACB e escolle o equipo co que xogas nesta liga.'}</p><button className="button" onClick={()=>{setDemo(false);setAccount(true);}}>A miña conta e o meu equipo <ArrowRight size={16}/></button></div>
   {ref&&!hidden&&<div className="panel side-card"><h3>Canto vos parecedes?</h3><p>Compara con</p><Picker label="Equipo de referencia" value={ref.userId} onChange={setReference} options={lineups.map(t=>({id:t.userId,name:t.name}))}/>{lineups.filter(t=>t.userId!==ref.userId).map(t=><div key={t.userId}><div className="pair"><span>{t.name}</span><b>{overlap(ref,t)} / {ref.players.length}</b></div><div className="meter"><span style={{width:`${overlap(ref,t)/ref.players.length*100}%`}}/></div></div>)}</div>}</div>}</div>}
  </>}
  <footer className="footer">Quinteto · Unha miniweb entre amigos. Sen afiliación coa ACB.{!demo&&' · Axuste manual por xornada: puntos dos xogadores novos menos puntos dos anteriores, só para cambios despois da declaración inicial e durante a xornada. Positivo resta; negativo suma. Antes da declaración, antes do inicio e entre xornadas: sen penalización. Os cambios feitos e desfeitos entre consultas non se poden detectar coa API actual.'}</footer></div></main>
  <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal('');}}><DialogContent showCloseButton={false}><DialogClose className="absolute right-4 top-4" aria-label="Pechar" disabled={busy}>×</DialogClose><DialogHeader><DialogTitle>{modal==='connect'?'Conecta a túa conta ACB':'Abrir unha xornada'}</DialogTitle><DialogDescription>{modal==='connect'?'Usamos o teu contrasinal só para iniciar sesión en ACB. Non o gardamos.':'Indica o inicio real da xornada: ata entón os equipos estarán ocultos. Os cambios posteriores á declaración inicial e durante a xornada rexístranse para o axuste manual de puntos.'}</DialogDescription></DialogHeader>
   {error&&<p className="error" role="alert">{error}</p>}
   {modal==='connect'?<form className="form" onSubmit={async e=>{const body=formData(e);e.currentTarget.reset();try{const result=await run('connect',body,'Conta conectada');if(result){setModal('');setAccount(true);}}finally{delete body.password;}}}><label>Usuario ou correo electrónico ACB<input name="username" autoComplete="username" required maxLength={200}/></label><label>Contrasinal ACB<input name="password" type="password" autoComplete="current-password" required maxLength={512}/></label><p>ACB validará os teus datos. Se solicita outro paso, mostrarase o aviso correspondente.</p><button className="button primary" disabled={busy}>{busy?'Conectando…':'Conectar e consultar os meus equipos'}</button></form>:<form className="form" onSubmit={async e=>{const form=formData(e);const result=await run('round',{label:form.label,lockAt:new Date(String(form.lockAt)).getTime(),endsAt:new Date(String(form.endsAt)).getTime()},'Xornada aberta');if(result)setModal('');}}><label>Nome<input name="label" placeholder="2026/27 · Xornada 1" required maxLength={50}/></label><label>Inicio (hora deste dispositivo)<input type="datetime-local" name="lockAt" required/></label><label>Final (hora deste dispositivo)<input type="datetime-local" name="endsAt" required/></label><p>O horario configúrase manualmente. Importade os cadros antes do inicio para poder calcular as penalizacións. Ao chegar a hora final deixan de contarse cambios. Entre xornadas os cambios son gratuítos.</p><button className="button primary" disabled={busy}>Abrir xornada</button></form>}
  </DialogContent></Dialog>
  <Dialog open={!!invite} onOpenChange={open=>{if(!open)setInvite('');}}><DialogContent showCloseButton={false}><DialogClose className="absolute right-4 top-4" aria-label="Pechar" disabled={busy}>×</DialogClose><DialogHeader><DialogTitle>Convite á vosa liga</DialogTitle><DialogDescription>Comparte este código cos teus amigos. Xerar un novo invalida o anterior.</DialogDescription></DialogHeader><code style={{overflowWrap:'anywhere',padding:15,background:'#edf1f6',borderRadius:8}}>{invite}</code><button className="button primary" onClick={()=>navigator.clipboard.writeText(invite).then(()=>toast.success('Código copiado')).catch(()=>toast.error('Selecciona o código para copialo.'))}>Copiar código</button><p className="subtle">O código serve para unirse á liga na primeira entrada. Cada persoa debe identificarse coa súa propia conta ACB.</p></DialogContent></Dialog>
  <AlertDialog open={closeRound} onOpenChange={setCloseRound}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Rematar a xornada?</AlertDialogTitle><AlertDialogDescription>Conservaranse os últimos cadros e as penalizacións detectadas. Xa non se admitirán máis importacións nesta xornada.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Volver</AlertDialogCancel><AlertDialogAction onClick={()=>void run('close-round',{roundId:openRound?.id},'Xornada rematada')}>Rematar xornada</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <AlertDialog open={!!removeMember} onOpenChange={open=>{if(!open&&!busy)setRemoveMember(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Eliminar a {removeMember?.name} da liga?</AlertDialogTitle><AlertDialogDescription>Eliminaranse os seus cadros, puntuacións e acceso a esta liguiña. Non se pode desfacer. A súa conta ACB non se modifica. A túa conta de administrador conservarase.</AlertDialogDescription></AlertDialogHeader>{error&&<p className="error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();const result=await run('remove-member',{userId:removeMember?.id},'Participante eliminado');if(result)setRemoveMember(null);}}>{busy?'Eliminando…':'Eliminar participante'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <Toaster containerAriaLabel="Notificacións"/>
 </div>;
}
