'use client';
import {useState,useEffect,useRef} from 'react';
import {pollScores} from '@/lib/score-polling';
import type {Round} from '@/lib/model';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
async function request(action:string,body:Record<string,unknown>={}){const r=await fetch('/api/league',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});const data=await r.json() as {error?:string;skipped?:boolean;updated:number;pending:number;journeys:{id:string;number:number}[];events:Event[];next:number|null};if(!r.ok)throw new Error(data.error??'Non se puido completar a operación.');return data;}
export function ScoreRefresh({round,onUpdated}:{round:Round;onUpdated:()=>Promise<unknown>}){
 const [automatic,setAutomatic]=useState(false);const inFlight=useRef(false);const tick=useRef<()=>void>(()=>{});
 const [number,setNumber]=useState(String(round.rinconJourneyNumber??round.acbJourneyNumber??''));const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(!automatic)return;if(round.closedAt!==null||round.endsAt<=Date.now()){setAutomatic(false);return;}return pollScores(()=>tick.current(),()=>{setAutomatic(false);setMessage('Actualizacións paradas: a xornada rematou.');},round.endsAt);},[automatic,round.endsAt,round.closedAt]);
 async function run(auto=false){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{
  const result=await request('refresh-rincon-scores',{roundId:round.id,journeyNumber:round.rinconJourneyNumber??Number(number),automatic:auto});
  await onUpdated();setMessage(result.skipped?'Hai unha consulta recente ou en curso. Conservamos os datos gardados.':result.updated+' equipos actualizados.'+(result.pending?' '+result.pending+' puntuacións pendentes ou conservadas da consulta anterior.':''));
 }catch(e){setAutomatic(false);setError(e instanceof Error?e.message:'Non se puido consultar Rincón.');}finally{inFlight.current=false;setBusy(false);}}
 tick.current=()=>{void run(true);};
 return <section className="panel" style={{padding:20,marginBottom:16}}><h3>Puntuacións e broker · Rincón del Manager</h3><p className="subtle">Puntos SuperManager co bonus incluído. Broker = prezo inicial + variación publicada. Non modifica cadros nin axustes.</p>
 {round.rinconJourneyNumber?<p>Xornada vinculada: {round.rinconJourneyNumber} · {round.rinconSeason}</p>:<label className="action-row">Número de xornada de Rincón <input aria-label="Número de xornada de Rincón" type="number" min={1} max={50} step={1} value={number} disabled={busy||automatic} onChange={e=>setNumber(e.target.value)}/><span className="subtle">Comproba que corresponde a «{round.label}». Quedará vinculada na primeira actualización correcta.</span></label>}
 <div className="action-row"><button className="button primary" disabled={busy||!number} onClick={()=>void run()}>{busy?'Consultando Rincón…':round.closedAt!==null||round.endsAt<=Date.now()?'Actualizar resultados finais':'Actualizar puntuacións'}</button><button className="button" disabled={!automatic&&(busy||!number||round.closedAt!==null||round.endsAt<=Date.now())} onClick={()=>{if(automatic)setAutomatic(false);else{setAutomatic(true);void run(true);}}}>{automatic?'Parar actualizacións automáticas':'Actualizacións automáticas'}</button></div>
 <p className="subtle" role="status">{automatic?'● Activas: cada 2 minutos mentres a web estea aberta.':'Actualizacións automáticas desactivadas.'} Pararán ao rematar a xornada. Nas xornadas rematadas consúltanse as fichas históricas dos xogadores de Rincón.</p>
 {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
type Event={id:number;at:number;user:string;message:string};
export function AuditLog(){const [events,setEvents]=useState<Event[]>([]);const [opened,setOpened]=useState(false);const [next,setNext]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(older=false){setBusy(true);setError('');try{const result=await request('audit',older&&next?{before:next}:{});setEvents(old=>older?[...old,...result.events]:result.events);setNext(result.next);setOpened(true);}catch(e){setError(e instanceof Error?e.message:'Non se puido cargar o rexistro.');}finally{setBusy(false);}}
 return <section className="panel" style={{padding:24,gridColumn:'1 / -1'}}><h2>Rexistro privado do administrador</h2><p className="subtle">Só datas, participantes e mensaxes resumidas. Non inclúe contrasinais nin identidades dos xogadores cambiados. Rexístrase actividade desde a activación desta función; as consultas automáticas requiren a web aberta e a conexión ACB vixente.</p><button className="button" disabled={busy} onClick={()=>void load()}>{opened?'Actualizar rexistro':'Ver rexistro'}</button>{error&&<p className="error" role="alert">{error}</p>}{opened&&<><Table><TableHeader><TableRow><TableHead>Data e hora · Madrid</TableHead><TableHead>Usuario</TableHead><TableHead>Actividade</TableHead></TableRow></TableHeader><TableBody>{events.map(e=><TableRow key={e.id}><TableCell>{new Date(e.at).toLocaleString('gl-ES',{timeZone:'Europe/Madrid'})}</TableCell><TableCell>{e.user}</TableCell><TableCell>{e.message}</TableCell></TableRow>)}</TableBody></Table>{!events.length&&<p>Aínda non hai actividade rexistrada.</p>}{next&&<button className="button" disabled={busy} onClick={()=>void load(true)}>Ver anteriores</button>}</>}</section>;
}
