'use client';
import {useState,useEffect,useRef} from 'react';
import {pollScores} from '@/lib/score-polling';
import type {Round} from '@/lib/model';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
async function request(action:string,body:Record<string,unknown>={}){const r=await fetch('/api/league',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});const data=await r.json() as {error?:string;updated:number;pending:number;journeys:{id:string;number:number}[];events:Event[];next:number|null};if(!r.ok)throw new Error(data.error??'Non se puido completar a operación.');return data;}
export function ScoreRefresh({round,onUpdated}:{round:Round;onUpdated:()=>Promise<unknown>}){
 const [automatic,setAutomatic]=useState(false);const inFlight=useRef(false);const latest=useRef({round,onUpdated});latest.current={round,onUpdated};const tick=useRef<()=>void>(()=>{});
 useEffect(()=>{if(!automatic)return;const remaining=round.endsAt-Date.now();if(round.closedAt!==null||remaining<=0){setAutomatic(false);return;}return pollScores(()=>tick.current(),()=>{setAutomatic(false);setMessage('Actualizacións automáticas paradas: a xornada rematou.');},round.endsAt);},[automatic,round.endsAt,round.closedAt]);
 const [list,setList]=useState<{id:string;number:number}[]>([]);const [selected,setSelected]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 async function run(refresh:boolean,auto=false){if(inFlight.current)return;if(auto&&(latest.current.round.closedAt!==null||latest.current.round.endsAt<=Date.now())){setAutomatic(false);return;}inFlight.current=true;setBusy(true);setError('');setMessage('');try{
  if(refresh){const result=await request('refresh-scores',{roundId:round.id,journeyId:round.acbJourneyId??selected,automatic:auto});await latest.current.onUpdated();setMessage(`${result.updated} equipos actualizados. ${result.pending} xogadores sen puntuación publicada; os totais en directo móstranse como parciais.`);}
  else {const result=await request('acb-journeys');setList(result.journeys);}
 }catch(e){setAutomatic(false);setError(e instanceof Error?e.message:'Non se puideron consultar as puntuacións.');}finally{inFlight.current=false;setBusy(false);}}
 tick.current=()=>{void run(true,true);};
 return <section className="panel" style={{padding:20,marginBottom:16}}><h3>Puntuacións de SuperManager ACB</h3><p className="subtle">Consulta os últimos puntos publicados por ACB para os xogadores dos cadros gardados. Non cambia as plantillas.</p>{round.acbJourneyId?<p>Xornada ACB vinculada: {round.acbJourneyNumber}</p>:<><button className="button" disabled={busy} onClick={()=>void run(false)}>Consultar xornadas ACB</button>{list.length>0&&<label style={{display:'block',marginTop:12}}>Xornada ACB correspondente a «{round.label}» <select aria-label="Xornada ACB" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Escolle a xornada</option>{list.map(j=><option key={j.id} value={j.id}>Xornada {j.number}</option>)}</select><p className="subtle">Comproba o número: quedará vinculado ao gardar as primeiras puntuacións.</p></label>}</>}
 <div className="action-row"><button className="button primary" disabled={busy||(!round.acbJourneyId&&!selected)} onClick={()=>void run(true)}>{busy?'Consultando ACB…':'Actualizar puntuacións'}</button><button className="button" disabled={!automatic&&(busy||(!round.acbJourneyId&&!selected)||round.closedAt!==null||round.endsAt<=Date.now())} onClick={()=>{if(automatic){setAutomatic(false);setMessage('Actualizacións automáticas paradas.');}else{setAutomatic(true);void run(true,true);}}}>{automatic?'Parar actualizacións automáticas':'Actualizacións automáticas'}</button></div><p className="subtle" role="status">{automatic?'● Activas: consulta cada 2 minutos mentres esta web estea aberta.':'Actualizacións automáticas desactivadas.'} Pararán ao rematar a xornada ou cambiar de xornada. Unha consulta xa enviada pode rematar.</p>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
type Event={id:number;at:number;user:string;message:string};
export function AuditLog(){const [events,setEvents]=useState<Event[]>([]);const [opened,setOpened]=useState(false);const [next,setNext]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(older=false){setBusy(true);setError('');try{const result=await request('audit',older&&next?{before:next}:{});setEvents(old=>older?[...old,...result.events]:result.events);setNext(result.next);setOpened(true);}catch(e){setError(e instanceof Error?e.message:'Non se puido cargar o rexistro.');}finally{setBusy(false);}}
 return <section className="panel" style={{padding:24,gridColumn:'1 / -1'}}><h2>Rexistro privado do administrador</h2><p className="subtle">Só datas, participantes e mensaxes resumidas. Non inclúe contrasinais nin identidades dos xogadores cambiados. Rexístrase actividade desde a activación desta función; as consultas automáticas requiren a web aberta e a conexión ACB vixente.</p><button className="button" disabled={busy} onClick={()=>void load()}>{opened?'Actualizar rexistro':'Ver rexistro'}</button>{error&&<p className="error" role="alert">{error}</p>}{opened&&<><Table><TableHeader><TableRow><TableHead>Data e hora · Madrid</TableHead><TableHead>Usuario</TableHead><TableHead>Actividade</TableHead></TableRow></TableHeader><TableBody>{events.map(e=><TableRow key={e.id}><TableCell>{new Date(e.at).toLocaleString('gl-ES',{timeZone:'Europe/Madrid'})}</TableCell><TableCell>{e.user}</TableCell><TableCell>{e.message}</TableCell></TableRow>)}</TableBody></Table>{!events.length&&<p>Aínda non hai actividade rexistrada.</p>}{next&&<button className="button" disabled={busy} onClick={()=>void load(true)}>Ver anteriores</button>}</>}</section>;
}
