'use client';
import {useState} from 'react';
import type {CatalogView,CatalogRow} from '@/lib/catalog';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
const labels:Record<CatalogRow['status'],string>={confirmed:'Confirmada',new:'Nova proposta',changed:'Con cambios',missing:'Ausente na fonte',pending:'Por resolver'};
type Selection={acbId:string;rinconRef:string};
export function CatalogReview(){
 const [catalog,setCatalog]=useState<CatalogView|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [page,setPage]=useState(0);const [draft,setDraft]=useState<Record<string,string>>({});const [review,setReview]=useState<Selection[]|null>(null);
 async function request(action:string,selections?:Selection[]){setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/league',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,revision:catalog?.revision,selections})});const result=await response.json() as CatalogView & {error?:string};if(!response.ok)throw new Error(result.error??'Non se puido completar a operación.');setCatalog(result as CatalogView);setDraft({});setReview(null);setPage(0);setMessage(action==='catalog-confirm'?'Equivalencias confirmadas.':action==='catalog-refresh'?'Catálogo actualizado. Revisa as novidades antes de confirmalas.':'Catálogo cargado.');}catch(e){setError(e instanceof Error?e.message:'Non se puido cargar o catálogo.');}finally{setBusy(false);}}
 const rows=catalog?.rows.filter(r=>(filter==='all'||r.status===filter)&&`${r.acb.name} ${r.acb.club} ${r.acb.ref} ${r.candidate?.name??''} ${r.confirmed?.rincon.name??''}`.toLocaleLowerCase('gl').includes(search.toLocaleLowerCase('gl')))??[];
 const used=new Set(catalog?.rows.flatMap(r=>r.confirmed?[r.confirmed.rincon.ref]:[])??[]);
 const proposals=catalog?.rows.filter(r=>r.status==='new'&&r.candidate&&!used.has(r.candidate.ref))??[];
 // Only batch candidates that are unique on both sides of the mapping.
 const unambiguous=proposals.filter(r=>proposals.filter(other=>other.candidate!.ref===r.candidate!.ref).length===1).slice(0,50).map(r=>({acbId:r.acb.ref,rinconRef:r.candidate!.ref}));
 return <section className="panel" style={{gridColumn:'1 / -1',minWidth:0}}><h2>Xogadores da nosa liga · só administrador</h2><p className="subtle">Revisa só os xogadores dos cadros gardados na nosa liga, tamén de xornadas anteriores. Recoméndase consultar o catálogo unha vez á semana. Esta revisión non modifica equipos, puntos nin penalizacións.</p>
 <div className="action-row"><button className="button" disabled={busy} onClick={()=>void request('catalog-read')}>{catalog?'Recargar catálogo':'Ver catálogo'}</button>{catalog&&<button className="button primary" disabled={busy||!!review} onClick={()=>void request('catalog-refresh')}>{busy?'Procesando…':'Actualizar catálogo'}</button>}</div>
 {error&&<p role="alert" className="error">{error}</p>}<p role="status">{message}</p>
 {catalog&&<><p>Tempada {catalog.season} · {catalog.acbCount} xogadores da liga presentes en ACB · {catalog.rinconCount} referencias relacionadas de Rincón.</p><p className="subtle">{catalog.checkedAt?`Última consulta: ${new Date(catalog.checkedAt).toLocaleString('gl-ES',{timeZone:'Europe/Madrid'})} (Madrid).`:'As equivalencias xa revisadas consérvanse. Actualiza para comprobar os xogadores da nosa liga.'} {catalog.reviewDue?'Revisión semanal pendente.':''}</p>
 <p className="subtle">Actualizar require a túa conexión ACB activa. As ausencias non se eliminan: poden ser temporais. As propostas novas só se gardan como equivalencias cando as confirmas.</p>
 <div className="action-row"><label>Buscar xogador <input style={{border:'1px solid #cbd5e1',borderRadius:8,padding:'8px 10px',maxWidth:'100%'}} value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Nome, club ou ID ACB"/></label><label>Estado <select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">Todos ({catalog.rows.length})</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label} ({catalog.rows.filter(r=>r.status===key).length})</option>)}</select></label></div>
 {!catalog.seedOnly&&unambiguous.length>0&&<button className="button" disabled={busy||!!review} onClick={()=>setReview(unambiguous)}>Revisar propostas inequívocas ({unambiguous.length})</button>}
 {review&&<section aria-label="Confirmación de equivalencias" style={{border:'2px solid #c2410c',borderRadius:12,padding:16,marginTop:16}}><h3>Confirma estas correspondencias</h3><p>Equivalencias para gardar: {review.length}. Comproba os nomes e clubs antes de continuar.</p><ul>{review.map(s=>{const row=catalog.rows.find(r=>r.acb.ref===s.acbId)!;const target=catalog.rincon.find(r=>r.ref===s.rinconRef)!;return <li key={s.acbId}>{row.acb.name} ({row.acb.club}, ID {s.acbId}) → {target.name} ({target.club}){row.confirmed&&row.confirmed.rincon.ref!==s.rinconRef?` · Substitúe ${row.confirmed.rincon.name}`:''}</li>;})}</ul><div className="action-row"><button className="button primary" disabled={busy} onClick={()=>void request('catalog-confirm',review)}>Confirmar equivalencias</button><button className="button" disabled={busy} onClick={()=>setReview(null)}>Cancelar</button></div></section>}
 <Table><TableHeader><TableRow><TableHead>Xogador ACB</TableHead><TableHead>Rincón del Manager</TableHead><TableHead>Revisión</TableHead></TableRow></TableHeader><TableBody>{rows.slice(page*25,(page+1)*25).map(row=>{const selected=draft[row.acb.ref]??row.candidate?.ref??'';return <TableRow key={row.acb.ref}><TableCell><strong>{row.acb.name}</strong><div>{row.acb.club} · {row.acb.position||'Posto pendente'} · ID {row.acb.ref}</div></TableCell><TableCell>{row.confirmed&&<p>Confirmada: {row.confirmed.rincon.name} ({row.confirmed.rincon.club})</p>}{!catalog.seedOnly&&row.acbPresent&&<label>Correspondencia para {row.acb.name}<select style={{display:'block',maxWidth:'min(280px,65vw)'}} aria-label={`Correspondencia de ${row.acb.name}`} disabled={busy||!!review} value={selected} onChange={e=>setDraft({...draft,[row.acb.ref]:e.target.value})}><option value="">Escolle un xogador</option>{[...catalog.rincon].sort((a,b)=>a.name.localeCompare(b.name,'gl')).map(p=><option key={p.ref} value={p.ref}>{p.name} · {p.club} · {p.position||'?'}</option>)}</select></label>}</TableCell><TableCell><strong>{labels[row.status]}</strong>{row.notes.map(n=><p className="subtle" key={n}>{n}</p>)}{!catalog.seedOnly&&row.acbPresent&&selected&&<button className="button" disabled={busy||!!review||(row.status==='confirmed'&&selected===row.confirmed?.rincon.ref)} onClick={()=>setReview([{acbId:row.acb.ref,rinconRef:selected}])}>Revisar</button>}</TableCell></TableRow>;})}</TableBody></Table>
 {!rows.length&&<p>Non hai xogadores con estes filtros.</p>}<div className="action-row"><button className="button" disabled={page===0} onClick={()=>setPage(page-1)}>Anterior</button><span>Páxina {page+1} de {Math.max(1,Math.ceil(rows.length/25))}</span><button className="button" disabled={(page+1)*25>=rows.length} onClick={()=>setPage(page+1)}>Seguinte</button></div></>}
 </section>;
}
