'use client';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import {quota} from '@/lib/quota';
import {clubCode} from '@/lib/catalog';
import type {Score} from '@/lib/model';
const teamDelta=(t:Lineup)=>{const values=t.players.map(p=>t.scores?.find(s=>s.id===p.id));return values.every(s=>s?.brokerDelta!=null&&!s.brokerStale)?values.reduce((sum,s)=>sum+s!.brokerDelta!,0):null;};
const signed=(n:number)=>(n>0?'+':'')+euros(n);
const euros=(n:number)=>new Intl.NumberFormat('gl-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
function Broker({score}:{score?:Score}){return <><b>{score?.broker==null?'—':euros(score.broker)}</b>{score?.broker!=null&&<small>{score.brokerStale?'Dato anterior':score.brokerKind==='opening'?'Prezo inicial':score.brokerKind==='final'?'Ao rematar o partido':'Provisional'}{score.brokerDelta!=null?' · '+(score.brokerDelta>0?'+':'')+euros(score.brokerDelta):''}</small>}</>;}
import {compare,type Lineup} from '@/lib/model';
import {livePoints,liveNet,sortPlayers} from '@/lib/live-scores';
const positionName=(position:string)=>({Alero:"Ala",Jugador:"Xogador"}[position]??position);
export default function LeagueBoard({lineups,tab,filter,hidden=false,sortBy="position",direction="asc",rosterUser=""}:{rosterUser?:string;sortBy?:string;direction?:string;lineups:Lineup[];tab:string;filter:string;hidden?:boolean}){
 const scoreFor=(id:string)=>[...lineups].sort((a,b)=>(b.scoresAt??0)-(a.scoresAt??0)).find(t=>t.scores?.some(s=>s.id===id))?.scores?.find(s=>s.id===id);
 const rows=sortPlayers(compare(lineups),sortBy,direction).filter(p=>(!rosterUser||p.owners.includes(rosterUser))&&(filter==='all'||(filter==='unique'?p.owners.length===1:p.owners.length===lineups.length)));
 if(!lineups.length)return <div className="panel empty"><h2>Aínda non hai cadros</h2><p>Conecta a túa conta, selecciona un equipo e abre unha xornada para comezar.</p></div>;
 if(tab==='teams')return <div className="cards">{lineups.map(t=><article className="panel team-card" key={t.userId}><h2>{t.team}</h2><p className="subtle">{t.name} · {t.players.length} xogadores</p><p className={`quota ${quota(t.players).status}`}>Cota galega: {quota(t.players).count}/2 mínimo · {quota(t.players).status==='valid'?'Cumpre':quota(t.players).status==='unknown'?'Pendente de comprobar':'Non cumpre'}</p>{!hidden&&<p className="penalty"><b>Axuste a restar: {t.penalty??0} puntos</b> · {t.changes??0} substitucións detectadas{(t.baselineKnown===false||t.history?.some(h=>h.pending))&&<span className="subtle" style={{display:'block'}}>Hai cambios sen hora verificable ou falta unha referencia: pendentes de revisión, sen desconto automático.</span>}</p>}{!!t.declaredAt&&<p className="subtle">Equipo inicial declarado polo xogador</p>}<p className="subtle">Importado: {new Date(t.importedAt).toLocaleString('gl-ES')}</p><p><b>{livePoints(t)??"—"} puntos ACB</b> · {liveNet(t)??"—"} tras penalizacións{t.scoresAt&&t.scores?.some(s=>s.points===null||s.stale)&&<small> · Parcial: faltan puntuacións</small>}</p><p><b>Variación total de broker: {teamDelta(t)===null?"—":signed(teamDelta(t)!)}</b>{teamDelta(t)===null&&<small>Datos de broker incompletos</small>}</p><ul>{sortPlayers(t.players).map(p=>{const changed=t.newPlayerIds?.includes(p.id);return <li key={p.id} style={changed?{color:'#14532d',fontStyle:'italic',fontWeight:700}:undefined}>{p.name}{t.scores&&<b style={{marginLeft:8}}>{t.scores.find(s=>s.id===p.id)?.didNotPlay?'—':t.scores.find(s=>s.id===p.id)?.points??'—'} pt</b>}<small>Broker: {t.scores?.find(s=>s.id===p.id)?.brokerDelta==null?"—":signed(t.scores.find(s=>s.id===p.id)!.brokerDelta!)}{t.scores?.find(s=>s.id===p.id)?.brokerStale?" · Dato anterior":""}</small><small style={changed?{color:'#14532d'}:undefined}>{clubCode(p.club??'Club por verificar')} · {positionName(p.position)}</small></li>})}</ul>{!hidden&&!!t.history?.length&&<details style={{marginTop:16}}><summary>Historial de cambios</summary>{t.history.map((entry,i)=><div key={i} className="subtle" style={{marginTop:12}}><b>{new Date(entry.at).toLocaleString('gl-ES')} · {entry.pending?'Pendente de revisión (sen desconto)':'Cambio rexistrado · axuste manual por xornada'}</b><p>Entran: {entry.incoming.map(p=>p.name).join(', ')}</p><p>Saen: {entry.outgoing.map(p=>p.name).join(', ')}</p></div>)}</details>}</article>)}</div>;
 return <div className="panel"><Table className="comparison"><TableHeader><TableRow><TableHead>XOGADOR</TableHead><TableHead>PUNTOS ACB</TableHead><TableHead>BROKER</TableHead>{lineups.map((t,i)=><TableHead key={t.userId}><div className="owner-head"><span className={`avatar a${i%4}`}>{t.name.slice(0,2).toUpperCase()}</span>{t.name}<small>{t.declaredAt?'✓ Inicial declarado':'◷ Sen declarar'}</small>{!hidden&&<small className="penalty">Axuste: {t.penalty??0} pt{t.baselineKnown===false||t.history?.some(h=>h.pending)?' *':''}</small>}</div></TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(p=><TableRow key={p.id} className={scoreFor(p.id)?.playing?'player-playing':undefined} title={scoreFor(p.id)?.playing?'En xogo: puntos e broker provisionais':undefined}><TableCell><span className="player-name">{p.name}</span><small>{positionName(p.position)} · {clubCode(p.club??"Club por verificar")}</small></TableCell><TableCell><b>{scoreFor(p.id)?.didNotPlay?"—":scoreFor(p.id)?.points??"—"}</b>{scoreFor(p.id)?.stale&&<small>Dato anterior</small>}</TableCell><TableCell><Broker score={scoreFor(p.id)}/></TableCell>{lineups.map(t=><TableCell key={t.userId}>{p.owners.includes(t.userId)?<span className={`check ${p.owners.length===1?'unique':''}`} aria-label={`No equipo de ${t.name}`}>✓</span>:<span className="dash" aria-label="Non o leva">—</span>}</TableCell>)}</TableRow>)}</TableBody></Table>{!rows.length&&<div className="empty">Non hai xogadores con este filtro.</div>}<p className="subtle" style={{padding:"12px 20px"}}>Fonte: {lineups.some(t=>t.scores?.some(s=>s.source==='rincon'))?'Rincón del Manager':'ACB / datos gardados'} · Consulta: {Math.max(...lineups.map(t=>t.scoresAt??0))?new Date(Math.max(...lineups.map(t=>t.scoresAt??0))).toLocaleString('gl-ES'):'Pendente'}</p><div className="legend"><span><i/>No cadro</span><span><i className="playing-key"/>En xogo: puntos e broker provisionais</span><span>* Horario non verificable: sen desconto automático</span><span><i className="orange"/>Só o leva un equipo</span></div></div>;
}
