'use client';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import {quota} from '@/lib/quota';
import {compare,type Lineup} from '@/lib/model';
import {livePoints,liveNet,sortPlayers} from '@/lib/live-scores';
const positionName=(position:string)=>({Alero:"Ala",Jugador:"Xogador"}[position]??position);
export default function LeagueBoard({lineups,tab,filter,hidden=false,sortBy="position",direction="asc",rosterUser=""}:{rosterUser?:string;sortBy?:string;direction?:string;lineups:Lineup[];tab:string;filter:string;hidden?:boolean}){
 const rows=sortPlayers(compare(lineups),sortBy,direction).filter(p=>(!rosterUser||p.owners.includes(rosterUser))&&(filter==='all'||(filter==='unique'?p.owners.length===1:p.owners.length===lineups.length)));
 if(!lineups.length)return <div className="panel empty"><h2>Aínda non hai cadros</h2><p>Conecta a túa conta, selecciona un equipo e abre unha xornada para comezar.</p></div>;
 if(tab==='teams')return <div className="cards">{lineups.map(t=><article className="panel team-card" key={t.userId}><h2>{t.team}</h2><p className="subtle">{t.name} · {t.players.length} xogadores</p><p className={`quota ${quota(t.players).status}`}>Cota galega: {quota(t.players).count}/2 mínimo · {quota(t.players).status==='valid'?'Cumpre':quota(t.players).status==='unknown'?'Pendente de comprobar':'Non cumpre'}</p>{!hidden&&<p className="penalty"><b>Axuste a restar: {t.penalty??0} puntos</b> · {t.changes??0} substitucións detectadas{(t.baselineKnown===false||t.history?.some(h=>h.pending))&&<span className="subtle" style={{display:'block'}}>Hai cambios sen hora verificable ou falta unha referencia: pendentes de revisión, sen desconto automático.</span>}</p>}{!!t.declaredAt&&<p className="subtle">Equipo inicial declarado polo xogador</p>}<p className="subtle">Importado: {new Date(t.importedAt).toLocaleString('gl-ES')}</p><p><b>{livePoints(t)??"—"} puntos ACB</b> · {liveNet(t)??"—"} tras penalizacións{t.scoresAt&&t.scores?.some(s=>s.points===null)&&<small> · Parcial: faltan puntuacións</small>}</p><ul>{sortPlayers(t.players).map(p=><li key={p.id}>{p.name}{t.scores&&<b style={{marginLeft:8}}>{t.scores.find(s=>s.id===p.id)?.points??'—'} pt</b>}<small>{p.club??'Club por verificar'} · {positionName(p.position)}</small></li>)}</ul>{!hidden&&!!t.history?.length&&<details style={{marginTop:16}}><summary>Historial de cambios</summary>{t.history.map((entry,i)=><div key={i} className="subtle" style={{marginTop:12}}><b>{new Date(entry.at).toLocaleString('gl-ES')} · {entry.pending?'Pendente de revisión (sen desconto)':'Cambio rexistrado · axuste manual por xornada'}</b><p>Entran: {entry.incoming.map(p=>p.name).join(', ')}</p><p>Saen: {entry.outgoing.map(p=>p.name).join(', ')}</p></div>)}</details>}</article>)}</div>;
 return <div className="panel"><Table className="comparison"><TableHeader><TableRow><TableHead>XOGADOR</TableHead><TableHead>PUNTOS ACB</TableHead>{lineups.map((t,i)=><TableHead key={t.userId}><div className="owner-head"><span className={`avatar a${i%4}`}>{t.name.slice(0,2).toUpperCase()}</span>{t.name}<small>{t.declaredAt?'✓ Inicial declarado':'◷ Sen declarar'}</small>{!hidden&&<small className="penalty">Axuste: {t.penalty??0} pt{t.baselineKnown===false||t.history?.some(h=>h.pending)?' *':''}</small>}</div></TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(p=><TableRow key={p.id}><TableCell><span className="player-name">{p.name}</span><small>{positionName(p.position)} · {p.club??"Club por verificar"}{p.owners.length===1?' · Aposta única':''}</small></TableCell><TableCell><b>{[...lineups].sort((a,b)=>(b.scoresAt??0)-(a.scoresAt??0)).find(t=>t.scores?.some(s=>s.id===p.id))?.scores?.find(s=>s.id===p.id)?.points??"—"}</b></TableCell>{lineups.map(t=><TableCell key={t.userId}>{p.owners.includes(t.userId)?<span className={`check ${p.owners.length===1?'unique':''}`} aria-label={`No equipo de ${t.name}`}>✓</span>:<span className="dash" aria-label="Non o leva">—</span>}</TableCell>)}</TableRow>)}</TableBody></Table>{!rows.length&&<div className="empty">Non hai xogadores con este filtro.</div>}<div className="legend"><span><i/>No cadro</span><span>* Horario non verificable: sen desconto automático</span><span><i className="orange"/>Só o leva un equipo</span></div></div>;
}
