'use client';
import {quota} from '@/lib/quota';
import {livePoints,liveNet} from '@/lib/live-scores';
import type {Lineup} from '@/lib/model';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
export default function Standings({lineups,demo,editable,busy,onScore,admin=false,onPenalty,metric="net"}:{metric?:string;admin?:boolean;onPenalty?:(userId:string,penalty:number)=>Promise<unknown>;lineups:Lineup[];demo:boolean;editable:boolean;busy:boolean;onScore:(userId:string,points:number)=>Promise<unknown>}){
 const sorted=[...lineups].sort((a,b)=>(quota(b.players).status!=="valid"?-Infinity:(metric==="acb"?livePoints(b):liveNet(b))??-Infinity)-(quota(a.players).status!=="valid"?-Infinity:(metric==="acb"?livePoints(a):liveNet(a))??-Infinity));
 return <section className="panel"><div className="panel-title"><div><h2>{metric==="acb"?"Puntos ACB":"Puntos tras penalizacións"}</h2><p>Axuste total da xornada = suma das diferenzas entre puntos dos xogadores novos e anteriores. Positivo resta; negativo suma. O administrador introdúceo manualmente; non se calcula aínda.</p></div></div><Table><TableHeader><TableRow><TableHead>Equipo</TableHead><TableHead>ACB</TableHead><TableHead>Axuste a restar</TableHead><TableHead>Total liga</TableHead></TableRow></TableHeader><TableBody>{sorted.map(t=><TableRow key={t.userId}><TableCell><b>{t.name}</b><p className="subtle">{t.declaredAt?'✓ Equipo inicial declarado':'◷ Pendente de declarar'}</p><p className="subtle">{t.team}</p><p className="subtle">Cota: {quota(t.players).count}/2{quota(t.players).status!=='valid'?' · Sen validar':''}</p></TableCell><TableCell>{editable?<form className="score-form" onSubmit={e=>{e.preventDefault();const points=Number(new FormData(e.currentTarget).get('points'));void onScore(t.userId,points);}}><input key={String(t.rawPoints)} aria-label={`Puntos ACB de ${t.name}`} name="points" type="number" min={-1000} max={10000} step="0.01" defaultValue={t.rawPoints??''} required/><button className="button" disabled={busy}>Gardar</button></form>:livePoints(t)??'—'}</TableCell><TableCell><b>{t.penalty??0}</b><p className="subtle">{t.changes??0} cambios detectados · axuste manual</p>{admin&&!!t.declaredAt&&<form className="score-form" onSubmit={e=>{e.preventDefault();void onPenalty?.(t.userId,Number(new FormData(e.currentTarget).get('penalty')));}}><input key={String(t.penalty)} aria-label={`Penalización de ${t.name}`} name="penalty" type="number" min={-10000} max={10000} step="0.01" defaultValue={t.penalty??0} required/><button className="button" disabled={busy}>Gardar axuste</button></form>}</TableCell><TableCell>{t.scoresAt&&<p className="subtle">ACB: {new Date(t.scoresAt).toLocaleString('gl-ES')}</p>}{t.scoresAt&&t.scores?.some(s=>s.points===null)&&<p className="subtle">Total parcial: faltan puntuacións de ACB.</p>}<strong>{quota(t.players).status==='valid'?(liveNet(t)??'—'):'Sen validar'}</strong>{(t.baselineKnown===false||t.history?.some(h=>h.pending))&&<p className="subtle">Provisional · revisar cambios</p>}</TableCell></TableRow>)}</TableBody></Table>{!lineups.length&&<p className="empty">Aínda non hai cadros rexistrados.</p>}<p className="subtle" style={{padding:20}}>{demo?'Exemplo: xogador novo −4, anterior 0 → axuste −4. Total da liga: puntos ACB − (−4).':'O administrador pode consultar os puntos publicados en ACB e gardalos durante a xornada. Ao rematar tamén pode corrixir manualmente o total. Só se axustan cambios posteriores á declaración inicial e durante a xornada. Gardar substitúe o axuste anterior; non o acumula.'}</p></section>;
}
