import { sqliteTable,text,integer,real,primaryKey,index,uniqueIndex } from 'drizzle-orm/sqlite-core';
export const leagues=sqliteTable('leagues',{id:text('id').primaryKey(),name:text('name').notNull(),ownerId:text('owner_id').notNull(),inviteHash:text('invite_hash').notNull()},t=>[uniqueIndex('idx_leagues_invite_hash').on(t.inviteHash)]);
export const members=sqliteTable('members',{userId:text('user_id').primaryKey(),leagueId:text('league_id').notNull().references(()=>leagues.id),name:text('name').notNull()},t=>[index('idx_members_league').on(t.leagueId)]);
export const links=sqliteTable('acb_links',{userId:text('user_id').primaryKey().references(()=>members.userId),jwt:text('jwt').notNull(),expiresAt:integer('expires_at').notNull(),teamId:text('team_id'),teamName:text('team_name'),teamsJson:text('teams_json').notNull()});
export const rounds=sqliteTable('rounds',{id:text('id').primaryKey(),leagueId:text('league_id').notNull().references(()=>leagues.id),label:text('label').notNull(),lockAt:integer('lock_at').notNull(),acbJourneyId:text('acb_journey_id'),acbJourneyNumber:integer('acb_journey_number'),closedAt:integer('closed_at'),endsAt:integer('ends_at').notNull().default(0)},t=>[index('idx_rounds_league_lock').on(t.leagueId,t.lockAt)]);
export const snapshots=sqliteTable('snapshots',{roundId:text('round_id').notNull().references(()=>rounds.id),userId:text('user_id').notNull().references(()=>members.userId),teamId:text('team_id').notNull(),teamName:text('team_name').notNull(),playersJson:text('players_json').notNull(),importedAt:integer('imported_at').notNull(),baselineJson:text('baseline_json'),changesCount:integer('changes_count').notNull().default(0),declaredAt:integer('declared_at'),rawPoints:real('raw_points'),manualPenalty:real('manual_penalty').notNull().default(0),penaltyReduction:real('penalty_reduction').notNull().default(0),scoresJson:text('scores_json'),scoresAt:integer('scores_at'),historyJson:text('history_json').notNull().default('[]')},t=>[primaryKey({columns:[t.roundId,t.userId]})]);
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('idx_rate_limits_expiry').on(t.expiresAt)]);
export const acbIdentities=sqliteTable('acb_identities',{acbId:text('acb_id').primaryKey(),userId:text('user_id').notNull().references(()=>members.userId)},t=>[uniqueIndex('idx_acb_identities_user').on(t.userId)]);
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>members.userId),expiresAt:integer('expires_at').notNull()},t=>[index('idx_sessions_user').on(t.userId)]);

export const auditEvents=sqliteTable('audit_events',{id:integer('id').primaryKey({autoIncrement:true}),leagueId:text('league_id').notNull(),userId:text('user_id').notNull(),userName:text('user_name').notNull(),at:integer('at').notNull(),message:text('message').notNull()},t=>[index('idx_audit_league_id').on(t.leagueId,t.id)]);
export const rosterObservations=sqliteTable('roster_observations',{userId:text('user_id').primaryKey().references(()=>members.userId),teamId:text('team_id').notNull(),idsJson:text('ids_json').notNull(),observedAt:integer('observed_at').notNull()});
